projectConfig:
  name: demo
  path: http://localhost:8078
  testUrl: #表示要测试的URL
    - url: /testPool
      type: get
    - url: /executeTask
      type: get
    - url: /testNull
      type: get
    - url: /testCachePool
      type: get
swaggerConfig:
  enable: true
  path: /api/swagger-ui.html#/
  docPath: /api/v2/api-docs