projectConfig:
  name: demo
  path: http://localhost:8078
  swaggerPath: /api/swagger-ui.html
  swaggerDoc: /v2/api-docs
  testUrl: #表示要测试的URL
    - url: /testPool
      type: get
    - url: /executeTask
      type: get
    - url: /testNull
      type: get
    - url: /testCachePool
      type: get